config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :users

  root 'homes#index'

end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :password
	EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
	validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
	validates :password, :confirmation => true #password_confirmation attr
	validates_length_of :password, :in => 6..20, :on => :create

	require 'digest/sha1'

	before_save :encrypt_password
	
	after_save :clear_password

	attr_accessible :username, :email, :password, :password_confirmation, :profile_image, :token

	def encrypt_password
		if password.present?
			self.salt = BCrypt::Engine.generate_salt
			self.encrypted_password= BCrypt::Engine.hash_secret(password, salt)
		end
	end

	def clear_password
		self.password = nil
	end

	def authenticate(password)
		if self && self.encrypted_password == BCrypt::Engine.hash_secret(password, self.salt)
			true
		else
			false
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :user_authenticate!

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	helper_method :current_user

	def user_authenticate!
		unless current_user.present? 
			redirect_to root_path
		end
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	skip_before_filter :user_authenticate!
	def index
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	skip_before_filter :user_authenticate!, only: [:new, :create]
	def new
	end
	def create
		@user = User.find_by_email(params[:email])
		if @user && @user.authenticate(params[:password])
			if @user.status == 'active'
				p 'session[:user_id] = @user.id'
				p session[:user_id] = @user.id
				redirect_to root_url, notice: 'Logged in!'
			else
				redirect_to root_url, notice: 'Your account is not active'
			end
		else
			render :new, notice: 'Invalid email & password'
		end
	end
	def destroy
		session[:user_id] = nil
		redirect_to root_url, notice: 'Logged out!'
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	skip_before_filter :user_authenticate!, only: [:new, :create]
	def index
	end

	def new
		@user = User.new 
	end

	def create
		@user = User.new(user_params)
		if @user.save
			p @token = Digest::SHA1.hexdigest([Time.zone.now, rand].join)
			p @user.update_attributes(token: @token, status: 'active')
			p 'session[:user_id] = @user.id'
			p session[:user_id] = @user.id
			# UserMailer.email_confirmation(@user)
			redirect_to root_path
			flash[:notice] = "You signed up successfully"
			flash[:color]= "valid"
		else
			flash[:notice] = "Form is invalid"
			flash[:color]= "invalid"
			render :new
		end
	end

	private

	def user_params
		params.require(:user).permit(:username, :email, :password, :password_confirmation, :profile_image, :token, :status)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/index.html.erb
<p>sasdas</p>
<%= session[:user_id] %>

app/views/layouts/_footer.html.erb
<div class="footer">
    <div class="pull-right">
       <%= link_to "About Us", "#" %>
    </div>
    <div>
        <strong>Copyright</strong> User Image 2016
    </div>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
    </div>
    <div id="navbar" class="collapse navbar-collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav navbar-right">
            <% if current_user.present? %>
              <li><%= link_to "Logout", logout_path %></li>
            <%else%>
              <li><%= link_to "Login", login_path %></li>
              <li><%= link_to "Sign up", new_user_path %></li>
            <%end%>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UserAuth</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
	<% flash.each do |message_type, message| %>
        <div id="flash"><%= message %></div>
    <% end %>
<div class="container-fluid">
<%= yield %>
</div>

<%= render 'layouts/footer' %>
</body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<% @page_title = "UserAuth | Signup" %>
<div class="Sign_Form">
  <h1>Sign Up</h1>
  <%= form_for(:user, :url => {:controller => 'users', :action => 'create'}) do |f| %>
    <p> Username:</br> <%= f.text_field :username%> </p>
    <p> Email:</br> <%= f.text_field :email%> </p>
    <p> Password:</br> <%= f.password_field :password%></p>
    <p> Password Confirmation:</br> <%= f.password_field :password_confirmation%> </p>
    <%= f.submit :Signup %>
  <% end %>
  <% if @user.errors.any? %>
    <ul class="Signup_Errors">
    <% for message_error in @user.errors.full_messages %>
      <li>* <%= message_error %></li>
    <% end %>
    </ul>
  <% end %>
</div>